on:
  pull_request:
  push:
    branches:
      - main

name: Continuous integration

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  test:
    name: Tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: make test

  cargo_deny:
    name: Cargo Deny
    uses: dusk-network/.github/.github/workflows/cargo-deny.yml@main
