on:
  pull_request:
  push:
    branches:
      - main

name: Continuous integration

jobs:
  code-quality:
    name: Code quality
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: cq

  test:
    name: Run tests
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: test

  cargo_deny:
    name: Cargo Deny
    uses: dusk-network/.github/.github/workflows/cargo-deny.yml@main
